[package]
name = "nbt_cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastnbt = "2.4.4"
serde = "1.0.196"
quartz_nbt = "0.2.8"
stupid_utils = "0.2.4"
